version: "3.9"
services:
  frontend:
    build: web-app/.
    volumes:
      - ./web-app/src/:/web_frontend/src
      - ./web-app/public/:/web_frontend/public
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
